### ISSUE TITLE
POST vs. PATCH?

### ISSUE THREAD

**Issue by harlanbarnes** [hartfordfive/ruby-grafana-api#4]
Hi there - First off, thanks for this rubygem, it's very helpful!

I did run into a problem however. I was trying write a little script to setup datasources during an initialization of grafana. I could read/GET the list of datasources and datasource types, but I couldn't create one. The grafana logs were complaining with:

```
"PATCH /api/datasources HTTP/1.1" 404 Not Found 23 bytes
```

As a test, I modified the gem to NOT translate a POST to a PATCH (instead just using a post) and all started working (around [here](https://github.com/lightspeedretail/ruby-grafana-api/blob/master/lib/grafana/http_request.rb#L37)).

I checked the [API docs](http://docs.grafana.org/reference/http_api/) and it looks like the PATCH verb is used for some of the update types, but not for create and delete.

Is there something I am missing on the use of PATCH here? If not, would you accept a PR to switch the usage of POST, PUT, and DELETE to use their corresponding verbs (instead of PATCH?)

Thanks!

**Comment by hartfordfive** [comment]
@harlanbarnes I apologize for the major delay in my response.  I had a filter that unintentionally set the message as read as soon as it came in so I'll fix that to prevent it from happening again!  I will take a look at this later on today or tomorrow when I have a chance and get back to you with a response.

**Comment by hartfordfive** [comment]
@harlanbarnes Thanks for finding that issue, it was a typo on my part. I had fixed that previously although failed to submit a PR and merge it to master.  I've fixed that in this [PR](https://github.com/lightspeedretail/ruby-grafana-api/pull/5).  Changes are visible in tag 0.1.2 and the updated v0.1.2 gem has also been pushed to [rubygems.org](https://rubygems.org/gems/grafana-api)

**Comment by harlanbarnes** [comment]
Thanks much! Again, I appreciate the gem.

**Comment by hartfordfive** [comment]
Glad you find it useful.  Don't hesitate to let others know about it.
